name: Info & Supply

on:
  schedule:
    # รันทุกวัน เวลา 00:00 UTC (07:00 เวลาไทย)
    # รูปแบบ: นาที ชั่วโมง วันที่ เดือน วันในสัปดาห์
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  runjobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Decryption Filter
        run: |
          git config filter.openssl-crypt.smudge "openssl enc -d -aes-256-cbc -pbkdf2 -iter 100000 -pass pass:${{ secrets.GIT_CRYPT_PASS }}"
          git config filter.openssl-crypt.clean "openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 -pass pass:${{ secrets.GIT_CRYPT_PASS }}"
          git checkout-index --force --all

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Service
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: CSI
        run: python cs.py